version: '3.8'

services:
  flask-container:
    image: duongvikhang/api-dashboard:v1.0.0
    container_name: flask-container
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:1@postgres-container:5433/ApiDashboardDB
    ports:
      - 50001:50000
    depends_on:
      - postgres-container
    networks:
      api-dashboard-network:
    volumes:
      - app:/api-dashboard
  
  postgres-container:
    image: duongvikhang/my-postgres:v1.0.0
    container_name: postgres-container
    environment:
      POSTGRES_DB: ApiDashboardDB
      POSTGRES_PASSWORD: 1
      PGPORT: 5433
    ports:
      - 5434:5433
    networks:
      api-dashboard-network:

networks:
  api-dashboard-network:
    name: api-dashboard-network
    driver: bridge

volumes:
  app:
  
     
