name: Run Tests

on:
  pull_request:
    branches:
      - Loi

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-html
          pip install selenium
          
      - name: Install Chrome WebDriver
        run: |
          LATEST_CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -L -o chromedriver.zip "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver.zip -d $HOME/.local/bin
      - name: Run tests
        run: |
          cd tests
          python -m pytest -v --html=ui_report.html UITest.py
          python -m pytest -v --html=login_report.html LoginTest.py
        
      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: Login Test Reports
          path: |
            test/login_report.html
            test/ui_report.html