name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10
      - name: Install Chrome WebDriver
        uses: nanasess/setup-chromedriver@v2
        with:
        # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-html
          pip install selenium

      - name: Run tests
        run: |
          cd tests
          python -m pytest -v --html=ui_report.html UITest.py
          python -m pytest -v --html=login_report.html LoginTest.py
        
      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: Login Test Reports
          path: |
            test/login_report.html
            test/ui_report.html