name: Run Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches: [ "main" ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-html
          pip install selenium
          pip install webdriver_manager
          pip install imapclient

      - name: Run tests
        run: |
          cd tests
          python -m pytest -v --html=ui_report.html UITest.py
          python -m pytest -v --html=login_report.html LoginTest.py
          python -m pytest -v --html=signup_report.html lSignUpTest.py
          python -m pytest -v --html=enteremail_report.html lEnterEmailTest.py
          python -m pytest -v --html=reset_report.html lResetPasswordTest.py
          python -m pytest -v --html=adData_report.html AdminDataTest.py
        
      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: |
            tests/ui_report.html
            tests/login_report.html
            tests/signup_report.html
            tests/enteremail_report.html
            tests/reset_report.html